pop-os/xdg-desktop-portal-cosmic

- data/cosmic.portal
- src/access.rs
- src/main.rs
In xdg-desktop-portal 1.15+, the screenshot interface would not be exposed if there is no Access implementation. Add a dummy one to make it work again.
According to my testing this dummy impl is not invoked when screenshot took place...
> Add a dummy implementation of Access

- Makefile
- data/cosmic-portals.conf
I noticed that I couldn't run apps like Fractal ( https://flathub.org/apps/org.gnome.Fractal ) in COSMIC, because there's no COSMIC implementation of the Secret portal ( https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Secret.html ) and the built-in implementation in `gnome-keyring` specifically only suggests to `xdg-desktop-portal` that it should be used in GNOME ( https://gitlab.gnome.org/GNOME/gnome-keyring/-/blob/master/daemon/gnome-keyring.portal )
Without a recommended per-desktop portal configuration file, `xdg-desktop-portal` can only rely on those `UseIn=` fields to figure out which implementations to use for which portals
The `UseIn=` field in *.portal files is deprecated in favour of per-desktop portal configuration files: …
> feat: portals configuration file; use `gnome-keyring` for Secrets portal

- Cargo.lock
- Cargo.toml
- examples/screencast.rs
- src/buffer.rs
- src/screencast.rs
- src/screencast_thread.rs
- src/wayland/mod.rs
I have an example that uses ashpd/gstreamer to get dmabufs from the pipewire stream. This could be expanded to take arguments to test different kinds of capture, using different GPUs, etc.
It works fine capturing an Intel output to a gstreamer `waylandsink` window, where Intel is the `main_device`. I can't seem to get vaapi or nvenc h264 encoding to work here (with different errors). When being careful to avoid copy to CPU.
Capturing the Nvidia output seems to fail here (xdg-desktop-portal cosmic is currently using dmabufs allocated with the `main_device` regardless of capture source). When I ran `wayland-1-renderD129 xdg-desktop-portal-cosmic` to capture with the Nvidia GPU, the compositor completely froze...
Anyway, this should be helpful for testing and improving …
> Testing / improvements for screencast portal

- Makefile
This PR removes some slashes in the makefile that I believe may be messing up my rpm builds. It's possible the issue is something else but nevertheless we can remove the unnecessary slashes.
> Remove unnecessary slashes in makefile

- src/screencast_thread.rs
- src/screenshot.rs
- src/wayland/mod.rs
This shouldn't change behavior, except that `WAYLAND_DEBUG=1` will show a lot fewer Wayland requests while capturing the screen. And perhaps some performance benefit, but I haven't specifically verified that.
The changes to how screencopy is handled should help for moving to the v2 screencopy protocol (https://github.com/pop-os/cosmic-protocols/pull/24).
> Don't create new screencopy session or wl_buffer each frame

- Cargo.lock
- src/app.rs
The change is probably not necessary after the update to libcosmic, but should be a better way of setting the color-scheme.
> fix: change color-schem on theme mode change

- src/screencast.rs
It seems these lines where missed in ddafa7b. And the attribute is ignored here instead of producing an error.
Fixes https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/46.
> fix: Change remaining `dbus_interface` uses to `zbus`

- examples/screencast.rs
[This](https://github.com/pop-os/xdg-desktop-portal-cosmic/commit/ddafa7b4506673abb8b219d1f8016ea87b3badb8#diff-8cd8df4f536f3b7978164bd2953e645b6f45b81e6fb552ffb3616e3cca74478b) change is incorrect, as `Debug` is implemented as `"OwnedFd({fd})"` (meaning `"fd={fd:?}"` becomes `"fd=OwnedFd(##)"`.
On a related note, I can't get the example to work, neither in Gnome, nor in COSMIC (both on ArchLinux). In both cases I get:
```
Error: Failed to link elements 'bin0' and 'bin1'
```
Interestingly in Gnome I get a dialog for choosing what to cast, but not in COSMIC. Perhaps this is not implemented yet, but I thought it was worth mentioning. If I set the sink to `filesink location=out.bin` I get `"Error: Element failed to change its state"`, which has got me a bit stumped (`GST_DEBUG` also show `no …
> Fix passing fd to pipewire in example.

- src/app.rs
Implements executing screenshot capture when the enter button is pressed.
Closes https://github.com/pop-os/cosmic-screenshot/issues/35
> feat: implement enter to confirm capture

- Cargo.lock
- Cargo.toml
- cosmic-portal-config/Cargo.toml
- cosmic-portal-config/src/lib.rs
- cosmic-portal-config/src/screenshot.rs
- src/app.rs
- src/main.rs
- src/screenshot.rs
- src/subscription.rs
Closes: pop-os/cosmic-screenshot#29
I tend to reuse the same screenshot settings much like the users in the linked issue. Currently, the portal uses a reasonable default, but it would be ideal to restore the last used options.
This patch implements the plumbing for configs as well as adds a config for the screenshot endpoint. It currently works, but I have to rebase the patch on master and support saving the selected output. The latter is a planned feature as per a comment in `screenshot.rs`.
The plumbing for configs should be useful in the future as well since there will likely be other settings to store for different endpoints.
- Force pushed to remove a finished to do and an unneeded clone
> feat: Restore last used screenshot settings

- Cargo.lock
- Cargo.toml
- examples/screencast.rs
- i18n/en/xdg_desktop_portal_cosmic.ftl
- src/app.rs
- src/main.rs
- src/screencast.rs
- src/screencast_dialog.rs
- src/screencast_thread.rs
- src/screenshot.rs
- src/subscription.rs
- src/wayland/mod.rs
- src/widget/keyboard_wrapper.rs
- src/widget/mod.rs
- src/widget/screenshot.rs
https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/48.
The screencast dialog here should work. But still needs various styling changes and various other things:
- Show preview of outputs. Icons of toplevels.
- Consider what type of source the client of the portal requested capture of, and if it allows multiple sources
* With multiple, how should we order them?
Capturing all monitors as a single source probably will need compositor support.
A screenshot dialog should be fairly easy, but isn't added yet.
> Screencast dialog

- flake.lock
- flake.nix
The flake has been broken for a while.
This updates the dependencies & configuration to make it work again.
Fixes #8:
There was a similar issue reported here: https://github.com/ipetkov/crane/issues/411
Adding `installCargoArtifactsMode = "use-zstd";` to `pkgDef` fixes the build issue here.
> Fix Nix flake

- cosmic-portal-config/src/screenshot.rs
- src/app.rs
- src/file_chooser.rs
- src/main.rs
- src/screencast.rs
- src/screencast_dialog.rs
- src/screencast_thread.rs
- src/subscription.rs
- src/widget/keyboard_wrapper.rs
Now the dialog is closed if the screencast request in cancelled over dbus. And the dialog is correctly updated if a request is made while the dialog is already running. This also makes some general code improvements.
The behavior of screen capture on Chromium, which is a bit weird given duplication with Chromium's own dialog, now seems to be more correct and match Gnome.
More changes will be needed to make sure `Request` and `Session` works exactly like they should (handling session `close` requests while dialog is running, emitting `closed`, etc.), but that doesn't seem to be too crucial.
> Improvements for screencast portal / dialog

- src/screenshot.rs
- src/widget/screenshot.rs
Closes: pop-os/cosmic-screenshot#54
Capturing a screenshot with an empty rectangle selection saves a mangled image. This patch disables the "capture" button for empty selections. It also checks for valid selections prior to capturing the screenshot.
> fix(screenshot): Don't save empty selection

- data/cosmic.portal
cosmic-session sets the `XDG_CURRENT_DESKTOP` variable to `COSMIC`. But the `cosmic.portal` file was expecting a lower-case `cosmic` value. That resulted in the portal not being launched.
Overwriting `XDG_CURRENT_DESKTOP` to `cosmic` was reported as a workaround by people facing the issue[0][1], but it's not a correct fix, since many other COSMIC subprojects are relying on the upper-case value. The right thing to do is to expect `COSMIC`, for consistency.
Fixes pop-os/xdg-desktop-portal-cosmic#93
[0] https://aur.archlinux.org/packages/cosmic-screenshot-git#comment-980452
[1] pop-os/cosmic-screenshot#3
> fix(data): Expect an upper-case value in `XDG_CURRENT_DESKTOP`

- src/access.rs
- src/app.rs
- src/file_chooser.rs
- src/main.rs
- src/screencast.rs
- src/screencast_dialog.rs
- src/screenshot.rs
- src/subscription.rs
May as well create a PR for some changes I've been working on, but more (larger) changes will be added later.
Apparently the access portal should be used for non-interactive screenshots, but that doesn't currently happen since `version` isn't advertised properly. That will also require the change from https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/88, and fixing up the `view` of the access dialog.
Not done yet (in the initial version of this PR):
* Make sure cancelling a request closes any dialog related to that request, for all dialogs
* Clean up and de-duplicate some of the dialog related code now that we have multiple dialogs
* Fix the access dialog
* Figure out how to handle portal requests to create a dialog when another dialog is open
- Does `xdg-desktop-portal` handle …
> Dialog improvements

- Cargo.toml
- src/main.rs
This reduced memory consumption of the service by 200 MB on my system. Seems a handful of our apps trigger this bug in glibc's malloc implementation.
https://github.com/pop-os/cosmic-bg/pull/73
> fix: set M_MMAP_THRESHOLD to prevent glibc memory fragmentation

- src/screencast_thread.rs
- src/wayland/mod.rs
This fixes screen capture if `xdg-desktop-portal-cosmic` is run on Sway. (And will be needed on cosmic-comp when the compositor properly handles buffer damage for screen capture.)
> screencast: Properly accumuate buffer damage and send to compositor

- src/app.rs
- src/screenshot.rs
- src/widget/rectangle_selection.rs
- src/widget/screenshot.rs
Fixes rounding error in rectangle selection, use subsurfaces (https://github.com/pop-os/xdg-desktop-portal-cosmic/pull/113), avoid image copy/transform until needed.
To fix https://github.com/pop-os/cosmic-screenshot/issues/87, this should also share the code used for non-interactive screenshots with rectangle selection.
> Fixes and improvements for screenshots

- src/screencast_dialog.rs
**changes tl;dr**
- when trying to screencast a specific toplevel, all icons display the fallback
- this pulls in the correct icons for each toplevel
> bugfix(screencast): add desktop entry icons to toplevel buttons

- src/screencast_thread.rs
- src/wayland/gbm_devices.rs
- src/wayland/mod.rs
Meant to address https://github.com/pop-os/xdg-desktop-portal-cosmic/issues/75.
It seems there isn't an intersection in the modifiers for the Nvidia device and Intel device, so this still isn't working (I guess Nvidia can't render to linear buffers). Maybe it should fallback to shm, but this is potentially something that could be improved, particularly if we don't normally render the Nvidia output on the Nvidia GPU since it has Intel surfaces open...
> Allocate buffers with `dmabuf_device` and modifiers advertised by image-copy-capture

- src/screencast_thread.rs
I seems to have gotten this working, after some testing and looking at the code in mutter and xdg-desktop-portal-wlr. (Pipewire's documentation isn't always that great.) I still need to clean up the implementation here.
This fixes capture of Nvidia outputs to an instance of OBS running on an Intel GPU, at the cost of falling back to shm capture.  Not sure if there's a good way to make sure this ends up doing more efficient GPU-to-GPU copies without relying on shm, but we'll want the fixes for shm fallback anyway, and we want to avoid implict modifiers in multi-GPU systems.
> screencast/pipewire: Don't allow implict modifiers, and fallback to shm if modifier isn't negotiated

- Makefile
This changes the install location from /usr/local/libexec to /usr/libexec which seems to be the appropriate place to install to. (for changes to actually take place).
> fixed makefile to install in the correct place.

- Cargo.lock
- Cargo.toml
I think the build failed before without the patch, but it doesn't seem to be failing when I test it now.
> cleanup: remove patch
